---
title: "Minimum Coins"
type: "challenge"
description: "Calculate the minimum number of coins needed."
depends: "rock-paper-scissors"
visibility: "assign"
ignore:
- "evening-exercise-minimum-coins.md"
